name: hiveapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.7.0
  json_serializable: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env